### ISSUE TITLE
希望能增加一个 转发几条抽奖动态后自动发原创动态的功能

### ISSUE THREAD

**Issue by SleepCC** [shanmite/Lottery#15]
因为现在抽奖号的判定比较严，连续转发很多抽奖动态很有可能被认为是抽奖号，各种抽奖工具就会直接过滤大大降低了抽到的概率

**Comment by shanmite** [comment]
发什么内容的动态呢

**Comment by andywang425** [comment]
我觉得可以抄其他人的动态。自己编辑动态内容的话太麻烦了。

**Comment by SleepCC** [comment]
不知道发带图动态实现起来会不会困难点。感觉目前最简单的方式是自己保存几个纯文字动态的模板随机发，就像随机评论那样

**Comment by shanmite** [comment]
主要是不知道主流抽奖工具的过滤原理是什么，有没有过滤机制，会判断源动态是否是抽奖吗，还是直接以转发动态的频率为依据

**Comment by SleepCC** [comment]
https://t.bilibili.com/493337857932400058?tab=2主要是今天看到这个动态想起来这个建议，暂不清楚官抽是什么原理
我后来又看到这个https://www.bilibili.com/read/cv4628878/，所以暂时我把转发频率设置成了10分钟一次_(: 」∠)_
https://www.bilibili.com/read/cv7527246这一篇也有一些过滤原理的猜测

**Comment by shanmite** [comment]
群里有不少人都中过官方抽奖了，官方抽奖应该是只过滤短时多次转发同一动态，和转发频率限制。非官方抽奖的开奖方式五花八门，有的连续转发两条抽奖动态都会被认定为抽奖号，可以考虑加一个模拟真人发动态的操作

**Comment by SleepCC** [comment]
了解了，那就麻烦作者了
