### ISSUE TITLE
建议整个白名单，有的动态有特殊要求

### ISSUE THREAD

**Issue by spiritLHL** [shanmite/Lottery#2]
有的动态要求发指定的内容，人工操作后如果再开脚本还是会转发这个有特殊要求的动态，造成重复转发评论，但其实是无效的转发，up不会理机器人转发(转发中不含特殊词汇)，建议开发一个动态白名单，名单里的动态脚本不再进行转发等相关操作

**Comment by shanmite** [comment]
额。。有点难度 要不转发之前弹出一个确认框
