### ISSUE TITLE
enhancement:一点增强建议

### ISSUE THREAD

**Issue by moetalk** [shanmite/Lottery#4]
提供 随机数值 功能（未验证）
在有些随机数值的变动（比如转发间隔时间），可能会防止官方的互动抽奖检测行为为异常数据吧（大概），这个只是一个猜测，因为以前抢辣条过于频繁也会隐性小黑屋不让抽辣条了

**Comment by shanmite** [comment]
随机数好像不管用，改封还得封，出现频繁问题时可以换一个IP试试
